Feat/cleanup
fsr5-fhaachen/portals pull request #456
Opened 2023-09-07 16:59 UTC by BenediktHaas96

Closes #85 

Removes many empty files (seeders and controllers primarily) and cleans up some old, unused or unwanted code

2023-09-07 18:18 UTC, TitusKirch approved these changes

2023-09-08 05:40 UTC, simonostendorf requested changes
can not verify that all removed controllers and seeders are not needed anymore but found a readded github action that should be removed here.

2023-09-08 05:40 UTC, simonostendorf commented on .github/workflows/release-chart.yml
This CI is not in our dev branch and should not be readded here.

2023-09-08 06:26 UTC, BenediktHaas96 commented on .github/workflows/release-chart.yml
Merged in dev branch, issue should be resolved now. Please verify

2023-09-08 06:31 UTC, simonostendorf commented on .github/workflows/release-chart.yml
Solved.

2023-09-08 06:32 UTC, simonostendorf approved these changes

2023-09-09 13:43 UTC, merged