feat: use presigned urls for s3
fsr5-fhaachen/portals pull request #666
Opened 2024-08-20 13:51 UTC by simonostendorf

closes #624

2024-08-22 10:10 UTC, TitusKirch requested changes

2024-08-22 10:10 UTC, TitusKirch commented on resources/js/composables/useS3.ts
> +  const uploadFileByPresignedUrl = async ({
I know this is my code from https://github.com/TitusKirch/saas-template/, so it's a bit weird to give feedback, but here in Portals we don't use objects as wrappers of the Parameter function in the composables. So it should look like this:

```ts
const uploadFileByPresignedUrl = async(
  file: File;
  presignedUrl: string
) {
//...
}
```

2024-08-22 10:10 UTC, TitusKirch commented on resources/js/components/user/EditModal.vue
> +      await uploadFileByPresignedUrl({
See change in `useS3`. It should look like this:

```ts
await uploadFileByPresignedUrl(
  formData.get("avatar"),
  data.presignedUrl.url,
);
```

2024-08-22 10:10 UTC, TitusKirch commented on resources/js/components/user/EditModal.vue
> +  var avatarPath = null;
It would be nicer to use a ref.

2024-08-22 22:10 UTC, TitusKirch requested changes

2024-08-22 22:10 UTC, TitusKirch commented on app/Http/Controllers/Api/ApiController.php
> +        //$path = 'avatars/' . $user->id . '/' . $fileName;
Remove commented out code

2024-08-22 22:10 UTC, TitusKirch commented on resources/js/components/user/EditModal.vue
> +  const avatarPath = ref<string | undefinded>(null);
You define the type as `string | undefinded` and then set it to `null`. This should then be `ref();` instead of `ref(null);`.

2024-08-22 22:10 UTC, TitusKirch commented on resources/js/components/user/EditModal.vue
> +      console.info("Avatar uploaded");
Remove console.info

2024-08-27 16:59 UTC, TitusKirch commented on resources/js/types/group.d.ts
> -    course_id: number | null;
Is available as `course?: Course | null;`.

2024-08-27 16:59 UTC, TitusKirch approved these changes

2024-09-07 10:16 UTC, TobiasGrether approved these changes

2024-09-07 10:24 UTC, merged